var dir_917c5facf8f36a924b8ca288d979ea82 =
[
    [ "Serialization", "dir_f6675e6efb3a306a0dc2b7ae78e91bd6.html", "dir_f6675e6efb3a306a0dc2b7ae78e91bd6" ],
    [ "Account.cs", "Account_8cs_source.html", null ],
    [ "AuthenticationResponse.cs", "AuthenticationResponse_8cs_source.html", null ],
    [ "Backtest.cs", "Backtest_8cs_source.html", null ],
    [ "BacktestReport.cs", "BacktestReport_8cs_source.html", null ],
    [ "BaseOptimization.cs", "BaseOptimization_8cs_source.html", null ],
    [ "Compile.cs", "Compile_8cs_source.html", null ],
    [ "CompileState.cs", "CompileState_8cs_source.html", null ],
    [ "Data.cs", "Data_8cs_source.html", null ],
    [ "Dividends.cs", "Api_2Dividends_8cs_source.html", null ],
    [ "Estimate.cs", "Estimate_8cs_source.html", null ],
    [ "LiveAlgorithm.cs", "LiveAlgorithm_8cs_source.html", null ],
    [ "LiveAlgorithmResults.cs", "LiveAlgorithmResults_8cs_source.html", null ],
    [ "LiveAlgorithmResultsJsonConverter.cs", "LiveAlgorithmResultsJsonConverter_8cs_source.html", null ],
    [ "LiveAlgorithmSettings.cs", "LiveAlgorithmSettings_8cs_source.html", null ],
    [ "LiveLog.cs", "LiveLog_8cs_source.html", null ],
    [ "Nodes.cs", "Nodes_8cs_source.html", null ],
    [ "Optimization.cs", "Optimization_8cs_source.html", null ],
    [ "OptimizationBacktest.cs", "OptimizationBacktest_8cs_source.html", null ],
    [ "OptimizationBacktestJsonConverter.cs", "OptimizationBacktestJsonConverter_8cs_source.html", null ],
    [ "Organization.cs", "Organization_8cs_source.html", null ],
    [ "ParameterSetJsonConverter.cs", "ParameterSetJsonConverter_8cs_source.html", null ],
    [ "Project.cs", "Project_8cs_source.html", null ],
    [ "ProjectFile.cs", "ProjectFile_8cs_source.html", null ],
    [ "ProjectNode.cs", "ProjectNode_8cs_source.html", null ],
    [ "RestResponse.cs", "RestResponse_8cs_source.html", null ],
    [ "Split.cs", "Api_2Split_8cs_source.html", null ]
];