var dir_a13f6f8007a79efa929662220c3a8033 =
[
    [ "AnnualReturnsReportElement.cs", "AnnualReturnsReportElement_8cs_source.html", null ],
    [ "AssetAllocationReportElement.cs", "AssetAllocationReportElement_8cs_source.html", null ],
    [ "CAGRReportElement.cs", "CAGRReportElement_8cs_source.html", null ],
    [ "ChartReportElement.cs", "ChartReportElement_8cs_source.html", null ],
    [ "CrisisReportElement.cs", "CrisisReportElement_8cs_source.html", null ],
    [ "CumulativeReturnsReportElement.cs", "CumulativeReturnsReportElement_8cs_source.html", null ],
    [ "DailyReturnsReportElement.cs", "DailyReturnsReportElement_8cs_source.html", null ],
    [ "DrawdownReportElement.cs", "DrawdownReportElement_8cs_source.html", null ],
    [ "EstimatedCapacityReportElement.cs", "EstimatedCapacityReportElement_8cs_source.html", null ],
    [ "ExposureReportElement.cs", "ExposureReportElement_8cs_source.html", null ],
    [ "InformationRatioReportElement.cs", "InformationRatioReportElement_8cs_source.html", null ],
    [ "IReportElement.cs", "IReportElement_8cs_source.html", null ],
    [ "LeverageUtilizationReportElement.cs", "LeverageUtilizationReportElement_8cs_source.html", null ],
    [ "MarketsReportElement.cs", "MarketsReportElement_8cs_source.html", null ],
    [ "MaxDrawdownReportElement.cs", "MaxDrawdownReportElement_8cs_source.html", null ],
    [ "MonthlyReturnsReportElement.cs", "MonthlyReturnsReportElement_8cs_source.html", null ],
    [ "ParametersReportElement.cs", "ParametersReportElement_8cs_source.html", null ],
    [ "PSRReportElement.cs", "PSRReportElement_8cs_source.html", null ],
    [ "ReportElement.cs", "ReportElement_8cs_source.html", null ],
    [ "ReturnsPerTradeReportElement.cs", "ReturnsPerTradeReportElement_8cs_source.html", null ],
    [ "RollingPortfolioBetaReportElement.cs", "RollingPortfolioBetaReportElement_8cs_source.html", null ],
    [ "RollingSharpeReportElement.cs", "RollingSharpeReportElement_8cs_source.html", null ],
    [ "RuntimeDaysReportElement.cs", "RuntimeDaysReportElement_8cs_source.html", null ],
    [ "SharpeRatioReportElement.cs", "SharpeRatioReportElement_8cs_source.html", null ],
    [ "SortinoRatioReportElement.cs", "SortinoRatioReportElement_8cs_source.html", null ],
    [ "TextReportElement.cs", "TextReportElement_8cs_source.html", null ],
    [ "TradesPerDayReportElement.cs", "TradesPerDayReportElement_8cs_source.html", null ],
    [ "TurnoverReportElement.cs", "TurnoverReportElement_8cs_source.html", null ]
];