var dir_501f194c7fda34b8b408ad3706a9a21d =
[
    [ "AlgoSeekFuturesConverter", "dir_f424370b0251e28ddbfcb9250dfbeb9a.html", "dir_f424370b0251e28ddbfcb9250dfbeb9a" ],
    [ "CoarseUniverseGenerator", "dir_1e329ac41e09a07f7e801e7fe9685dd8.html", "dir_1e329ac41e09a07f7e801e7fe9685dd8" ],
    [ "KaikoDataConverter", "dir_1afd458345b460a90f1cc4133b0388d4.html", "dir_1afd458345b460a90f1cc4133b0388d4" ],
    [ "RandomDataGenerator", "dir_d5226a0debcc5eb325d870c98ff76e83.html", "dir_d5226a0debcc5eb325d870c98ff76e83" ],
    [ "Bz2StreamProvider.cs", "Bz2StreamProvider_8cs_source.html", null ],
    [ "ConsolidatorDataProcessor.cs", "ConsolidatorDataProcessor_8cs_source.html", null ],
    [ "CsvDataProcessor.cs", "CsvDataProcessor_8cs_source.html", null ],
    [ "ExchangeInfoUpdater.cs", "ExchangeInfoUpdater_8cs_source.html", null ],
    [ "FactorFileGenerator.cs", "FactorFileGenerator_8cs_source.html", null ],
    [ "FileStreamProvider.cs", "FileStreamProvider_8cs_source.html", null ],
    [ "FilteredDataProcessor.cs", "FilteredDataProcessor_8cs_source.html", null ],
    [ "GzipStreamProvider.cs", "GzipStreamProvider_8cs_source.html", null ],
    [ "IDataProcessor.cs", "IDataProcessor_8cs_source.html", null ],
    [ "IExchangeInfoDownloader.cs", "IExchangeInfoDownloader_8cs_source.html", null ],
    [ "IStreamParser.cs", "IStreamParser_8cs_source.html", null ],
    [ "IStreamProvider.cs", "IStreamProvider_8cs_source.html", null ],
    [ "LazyStreamWriter.cs", "LazyStreamWriter_8cs_source.html", null ],
    [ "LeanDataReader.cs", "LeanDataReader_8cs_source.html", null ],
    [ "LeanInstrument.cs", "LeanInstrument_8cs_source.html", null ],
    [ "LeanParser.cs", "LeanParser_8cs_source.html", null ],
    [ "PipeDataProcessor.cs", "PipeDataProcessor_8cs_source.html", null ],
    [ "Program.cs", "ToolBox_2Program_8cs_source.html", null ],
    [ "RawFileProcessor.cs", "RawFileProcessor_8cs_source.html", null ],
    [ "TemporaryPathProvider.cs", "TemporaryPathProvider_8cs_source.html", null ],
    [ "TickAggregator.cs", "TickAggregator_8cs_source.html", null ],
    [ "ZipStreamProvider.cs", "ZipStreamProvider_8cs_source.html", null ]
];