var namespaceQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData =
[
    [ "BrokerageHistoryProvider", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1BrokerageHistoryProvider.html", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1BrokerageHistoryProvider" ],
    [ "FakeHistoryProvider", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1FakeHistoryProvider.html", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1FakeHistoryProvider" ],
    [ "HistoryProviderManager", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1HistoryProviderManager.html", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1HistoryProviderManager" ],
    [ "SineHistoryProvider", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1SineHistoryProvider.html", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1SineHistoryProvider" ],
    [ "SubscriptionDataReaderHistoryProvider", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1SubscriptionDataReaderHistoryProvider.html", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1SubscriptionDataReaderHistoryProvider" ],
    [ "SynchronizingHistoryProvider", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1SynchronizingHistoryProvider.html", "classQuantConnect_1_1Lean_1_1Engine_1_1HistoricalData_1_1SynchronizingHistoryProvider" ]
];