var namespaceQuantConnect_1_1Data_1_1Consolidators =
[
    [ "BaseDataConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1BaseDataConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1BaseDataConsolidator" ],
    [ "BaseTimelessConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1BaseTimelessConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1BaseTimelessConsolidator" ],
    [ "Calendar", "classQuantConnect_1_1Data_1_1Consolidators_1_1Calendar.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1Calendar" ],
    [ "CalendarInfo", "structQuantConnect_1_1Data_1_1Consolidators_1_1CalendarInfo.html", "structQuantConnect_1_1Data_1_1Consolidators_1_1CalendarInfo" ],
    [ "CalendarType", "classQuantConnect_1_1Data_1_1Consolidators_1_1CalendarType.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1CalendarType" ],
    [ "ClassicRangeConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1ClassicRangeConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1ClassicRangeConsolidator" ],
    [ "ClassicRenkoConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1ClassicRenkoConsolidator.html", null ],
    [ "DataConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1DataConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1DataConsolidator" ],
    [ "DynamicDataConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1DynamicDataConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1DynamicDataConsolidator" ],
    [ "FilteredIdentityDataConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1FilteredIdentityDataConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1FilteredIdentityDataConsolidator" ],
    [ "IDataConsolidator", "interfaceQuantConnect_1_1Data_1_1Consolidators_1_1IDataConsolidator.html", "interfaceQuantConnect_1_1Data_1_1Consolidators_1_1IDataConsolidator" ],
    [ "IdentityDataConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1IdentityDataConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1IdentityDataConsolidator" ],
    [ "OpenInterestConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1OpenInterestConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1OpenInterestConsolidator" ],
    [ "PeriodCountConsolidatorBase", "classQuantConnect_1_1Data_1_1Consolidators_1_1PeriodCountConsolidatorBase.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1PeriodCountConsolidatorBase" ],
    [ "QuoteBarConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1QuoteBarConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1QuoteBarConsolidator" ],
    [ "RangeConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1RangeConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1RangeConsolidator" ],
    [ "RenkoConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html", null ],
    [ "SequentialConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1SequentialConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1SequentialConsolidator" ],
    [ "TickConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1TickConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1TickConsolidator" ],
    [ "TickQuoteBarConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1TickQuoteBarConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1TickQuoteBarConsolidator" ],
    [ "TradeBarConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1TradeBarConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1TradeBarConsolidator" ],
    [ "TradeBarConsolidatorBase", "classQuantConnect_1_1Data_1_1Consolidators_1_1TradeBarConsolidatorBase.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1TradeBarConsolidatorBase" ],
    [ "VolumeRenkoConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1VolumeRenkoConsolidator.html", "classQuantConnect_1_1Data_1_1Consolidators_1_1VolumeRenkoConsolidator" ],
    [ "WickedRenkoConsolidator", "classQuantConnect_1_1Data_1_1Consolidators_1_1WickedRenkoConsolidator.html", null ]
];