var namespaceQuantConnect_1_1Securities_1_1CurrencyConversion =
[
    [ "ConstantCurrencyConversion", "classQuantConnect_1_1Securities_1_1CurrencyConversion_1_1ConstantCurrencyConversion.html", "classQuantConnect_1_1Securities_1_1CurrencyConversion_1_1ConstantCurrencyConversion" ],
    [ "ICurrencyConversion", "interfaceQuantConnect_1_1Securities_1_1CurrencyConversion_1_1ICurrencyConversion.html", "interfaceQuantConnect_1_1Securities_1_1CurrencyConversion_1_1ICurrencyConversion" ],
    [ "SecurityCurrencyConversion", "classQuantConnect_1_1Securities_1_1CurrencyConversion_1_1SecurityCurrencyConversion.html", "classQuantConnect_1_1Securities_1_1CurrencyConversion_1_1SecurityCurrencyConversion" ]
];