var namespaceQuantConnect_1_1Data_1_1UniverseSelection =
[
    [ "BaseDataCollection", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1BaseDataCollection.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1BaseDataCollection" ],
    [ "BaseFundamentalDataProvider", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1BaseFundamentalDataProvider.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1BaseFundamentalDataProvider" ],
    [ "CoarseFundamental", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1CoarseFundamental.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1CoarseFundamental" ],
    [ "CoarseFundamentalDataProvider", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1CoarseFundamentalDataProvider.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1CoarseFundamentalDataProvider" ],
    [ "CoarseFundamentalUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1CoarseFundamentalUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1CoarseFundamentalUniverse" ],
    [ "ConstituentsUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ConstituentsUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ConstituentsUniverse" ],
    [ "ConstituentsUniverseData", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ConstituentsUniverseData.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ConstituentsUniverseData" ],
    [ "ContinuousContractUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ContinuousContractUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ContinuousContractUniverse" ],
    [ "ETFConstituentData", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ETFConstituentData.html", null ],
    [ "ETFConstituentsUniverseFactory", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ETFConstituentsUniverseFactory.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ETFConstituentsUniverseFactory" ],
    [ "ETFConstituentUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ETFConstituentUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ETFConstituentUniverse" ],
    [ "FineFundamentalFilteredUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FineFundamentalFilteredUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FineFundamentalFilteredUniverse" ],
    [ "FineFundamentalUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FineFundamentalUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FineFundamentalUniverse" ],
    [ "FuncUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FuncUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FuncUniverse" ],
    [ "FundamentalFilteredUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FundamentalFilteredUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FundamentalFilteredUniverse" ],
    [ "FundamentalService", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FundamentalService.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FundamentalService" ],
    [ "FundamentalUniverseFactory", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FundamentalUniverseFactory.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FundamentalUniverseFactory" ],
    [ "FuturesChainUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FuturesChainUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1FuturesChainUniverse" ],
    [ "GetSubscriptionRequestsUniverseDecorator", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1GetSubscriptionRequestsUniverseDecorator.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1GetSubscriptionRequestsUniverseDecorator" ],
    [ "IFundamentalDataProvider", "interfaceQuantConnect_1_1Data_1_1UniverseSelection_1_1IFundamentalDataProvider.html", "interfaceQuantConnect_1_1Data_1_1UniverseSelection_1_1IFundamentalDataProvider" ],
    [ "ITimeTriggeredUniverse", "interfaceQuantConnect_1_1Data_1_1UniverseSelection_1_1ITimeTriggeredUniverse.html", "interfaceQuantConnect_1_1Data_1_1UniverseSelection_1_1ITimeTriggeredUniverse" ],
    [ "OptionChainUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1OptionChainUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1OptionChainUniverse" ],
    [ "ScheduledUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ScheduledUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1ScheduledUniverse" ],
    [ "SecurityChanges", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SecurityChanges.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SecurityChanges" ],
    [ "SecurityChangesConstructor", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SecurityChangesConstructor.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SecurityChangesConstructor" ],
    [ "SelectSymbolsUniverseDecorator", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SelectSymbolsUniverseDecorator.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SelectSymbolsUniverseDecorator" ],
    [ "SubscriptionRequest", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SubscriptionRequest.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1SubscriptionRequest" ],
    [ "Universe", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1Universe.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1Universe" ],
    [ "UniverseDecorator", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniverseDecorator.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniverseDecorator" ],
    [ "UniverseExtensions", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniverseExtensions.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniverseExtensions" ],
    [ "UniversePythonWrapper", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniversePythonWrapper.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniversePythonWrapper" ],
    [ "UniverseSettings", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniverseSettings.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UniverseSettings" ],
    [ "UserDefinedUniverse", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UserDefinedUniverse.html", "classQuantConnect_1_1Data_1_1UniverseSelection_1_1UserDefinedUniverse" ]
];