var namespaceQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1Analysis_1_1Providers =
[
    [ "AlgorithmSecurityValuesProvider", "classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1Analysis_1_1Providers_1_1AlgorithmSecurityValuesProvider.html", "classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1Analysis_1_1Providers_1_1AlgorithmSecurityValuesProvider" ],
    [ "DefaultInsightScoreFunctionProvider", "classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1Analysis_1_1Providers_1_1DefaultInsightScoreFunctionProvider.html", "classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1Analysis_1_1Providers_1_1DefaultInsightScoreFunctionProvider" ]
];