var namespaceQuantConnect_1_1AlgorithmFactory_1_1Python_1_1Wrappers =
[
    [ "AlgorithmPythonWrapper", "classQuantConnect_1_1AlgorithmFactory_1_1Python_1_1Wrappers_1_1AlgorithmPythonWrapper.html", "classQuantConnect_1_1AlgorithmFactory_1_1Python_1_1Wrappers_1_1AlgorithmPythonWrapper" ]
];