var searchData=
[
  ['randomdatagenerator_9373',['RandomDataGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomdatageneratorprogram_9374',['RandomDataGeneratorProgram',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGeneratorProgram.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomdatageneratorsettings_9375',['RandomDataGeneratorSettings',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGeneratorSettings.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randompricegenerator_9376',['RandomPriceGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomPriceGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomvaluegenerator_9377',['RandomValueGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomValueGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomvaluegeneratorexception_9378',['RandomValueGeneratorException',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomValueGeneratorException.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['rategate_9379',['RateGate',['../classQuantConnect_1_1Util_1_1RateGate.html',1,'QuantConnect::Util']]],
  ['ratelimitenumerator_9380',['RateLimitEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1RateLimitEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['rateofchange_9381',['RateOfChange',['../classQuantConnect_1_1Indicators_1_1RateOfChange.html',1,'QuantConnect::Indicators']]],
  ['rateofchangepercent_9382',['RateOfChangePercent',['../classQuantConnect_1_1Indicators_1_1RateOfChangePercent.html',1,'QuantConnect::Indicators']]],
  ['rateofchangeratio_9383',['RateOfChangeRatio',['../classQuantConnect_1_1Indicators_1_1RateOfChangeRatio.html',1,'QuantConnect::Indicators']]],
  ['rawfileprocessor_9384',['RawFileProcessor',['../classQuantConnect_1_1ToolBox_1_1RawFileProcessor.html',1,'QuantConnect::ToolBox']]],
  ['rawmaterialsbalancesheet_9385',['RawMaterialsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RawMaterialsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['readererrordetectedeventargs_9386',['ReaderErrorDetectedEventArgs',['../classQuantConnect_1_1ReaderErrorDetectedEventArgs.html',1,'QuantConnect']]],
  ['readererroreventargs_9387',['ReaderErrorEventArgs',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1ReaderErrorEventArgs.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['readerwriterlockslimextensions_9388',['ReaderWriterLockSlimExtensions',['../classQuantConnect_1_1Util_1_1ReaderWriterLockSlimExtensions.html',1,'QuantConnect::Util']]],
  ['readonlysecurityvaluescollection_9389',['ReadOnlySecurityValuesCollection',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1Analysis_1_1ReadOnlySecurityValuesCollection.html',1,'QuantConnect::Algorithm::Framework::Alphas::Analysis']]],
  ['realizedgainlossonsaleofloansandleasecashflowstatement_9390',['RealizedGainLossOnSaleOfLoansAndLeaseCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RealizedGainLossOnSaleOfLoansAndLeaseCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['realtimeprovider_9391',['RealTimeProvider',['../classQuantConnect_1_1RealTimeProvider.html',1,'QuantConnect']]],
  ['realtimescheduleeventservice_9392',['RealTimeScheduleEventService',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1RealTimeScheduleEventService.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['realtimesynchronizedtimer_9393',['RealTimeSynchronizedTimer',['../classQuantConnect_1_1RealTimeSynchronizedTimer.html',1,'QuantConnect']]],
  ['receiptsfromcustomerscashflowstatement_9394',['ReceiptsfromCustomersCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceiptsfromCustomersCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['receiptsfromgovernmentgrantscashflowstatement_9395',['ReceiptsfromGovernmentGrantsCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceiptsfromGovernmentGrantsCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivablesadjustmentsallowancesbalancesheet_9396',['ReceivablesAdjustmentsAllowancesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivablesAdjustmentsAllowancesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivablesbalancesheet_9397',['ReceivablesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivablesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivableturnover_9398',['ReceivableTurnover',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivableTurnover.html',1,'QuantConnect::Data::Fundamental']]],
  ['reconciledcostofrevenueincomestatement_9399',['ReconciledCostOfRevenueIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReconciledCostOfRevenueIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reconcileddepreciationincomestatement_9400',['ReconciledDepreciationIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReconciledDepreciationIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['ref_9401',['Ref',['../classQuantConnect_1_1Util_1_1Ref.html',1,'QuantConnect::Util']]],
  ['ref_3c_20timespan_20_3e_9402',['Ref&lt; TimeSpan &gt;',['../classQuantConnect_1_1Util_1_1Ref.html',1,'QuantConnect::Util']]],
  ['referencewrapper_9403',['ReferenceWrapper',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['referencewrapper_3c_20datetime_20_3e_9404',['ReferenceWrapper&lt; DateTime &gt;',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['referencewrapper_3c_20decimal_20_3e_9405',['ReferenceWrapper&lt; decimal &gt;',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['refreshenumerator_9406',['RefreshEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1RefreshEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['registeredsecuritydatatypesprovider_9407',['RegisteredSecurityDataTypesProvider',['../classQuantConnect_1_1Securities_1_1RegisteredSecurityDataTypesProvider.html',1,'QuantConnect::Securities']]],
  ['regressionchannel_9408',['RegressionChannel',['../classQuantConnect_1_1Indicators_1_1RegressionChannel.html',1,'QuantConnect::Indicators']]],
  ['regressionfileloghandler_9409',['RegressionFileLogHandler',['../classQuantConnect_1_1Logging_1_1RegressionFileLogHandler.html',1,'QuantConnect::Logging']]],
  ['regressiongrowthofdividends5years_9410',['RegressionGrowthofDividends5Years',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegressionGrowthofDividends5Years.html',1,'QuantConnect::Data::Fundamental']]],
  ['regressiongrowthoperatingrevenue5years_9411',['RegressionGrowthOperatingRevenue5Years',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegressionGrowthOperatingRevenue5Years.html',1,'QuantConnect::Data::Fundamental']]],
  ['regressionresulthandler_9412',['RegressionResultHandler',['../classQuantConnect_1_1Lean_1_1Engine_1_1Results_1_1RegressionResultHandler.html',1,'QuantConnect::Lean::Engine::Results']]],
  ['regularexpression_9413',['RegularExpression',['../classQuantConnect_1_1Util_1_1Validate_1_1RegularExpression.html',1,'QuantConnect::Util::Validate']]],
  ['regulatoryassetsbalancesheet_9414',['RegulatoryAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegulatoryAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['regulatoryliabilitiesbalancesheet_9415',['RegulatoryLiabilitiesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegulatoryLiabilitiesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsuranceandotherrecoveriesreceivedcashflowstatement_9416',['ReinsuranceandOtherRecoveriesReceivedCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceandOtherRecoveriesReceivedCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsuranceassetsbalancesheet_9417',['ReinsuranceAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancebalancespayablebalancesheet_9418',['ReinsuranceBalancesPayableBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceBalancesPayableBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoverablebalancesheet_9419',['ReinsuranceRecoverableBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoverableBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesclaimsandbenefitsincomestatement_9420',['ReinsuranceRecoveriesClaimsandBenefitsIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesClaimsandBenefitsIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesofinsuranceliabilitiesincomestatement_9421',['ReinsuranceRecoveriesofInsuranceLiabilitiesIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesofInsuranceLiabilitiesIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesofinvestmentcontractincomestatement_9422',['ReinsuranceRecoveriesofInvestmentContractIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesofInvestmentContractIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['relativedailyvolume_9423',['RelativeDailyVolume',['../classQuantConnect_1_1Indicators_1_1RelativeDailyVolume.html',1,'QuantConnect::Indicators']]],
  ['relativemovingaverage_9424',['RelativeMovingAverage',['../classQuantConnect_1_1Indicators_1_1RelativeMovingAverage.html',1,'QuantConnect::Indicators']]],
  ['relativestandarddeviationvolatilitymodel_9425',['RelativeStandardDeviationVolatilityModel',['../classQuantConnect_1_1Securities_1_1RelativeStandardDeviationVolatilityModel.html',1,'QuantConnect::Securities']]],
  ['relativestrengthindex_9426',['RelativeStrengthIndex',['../classQuantConnect_1_1Indicators_1_1RelativeStrengthIndex.html',1,'QuantConnect::Indicators']]],
  ['relativevigorindex_9427',['RelativeVigorIndex',['../classQuantConnect_1_1Indicators_1_1RelativeVigorIndex.html',1,'QuantConnect::Indicators']]],
  ['relativevigorindexsignal_9428',['RelativeVigorIndexSignal',['../classQuantConnect_1_1Indicators_1_1RelativeVigorIndexSignal.html',1,'QuantConnect::Indicators']]],
  ['remotefilesubscriptionstreamreader_9429',['RemoteFileSubscriptionStreamReader',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Transport_1_1RemoteFileSubscriptionStreamReader.html',1,'QuantConnect::Lean::Engine::DataFeeds::Transport']]],
  ['removedmember_9430',['RemovedMember',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1PendingRemovalsManager_1_1RemovedMember.html',1,'QuantConnect::Lean::Engine::DataFeeds::PendingRemovalsManager']]],
  ['renkobar_9431',['RenkoBar',['../classQuantConnect_1_1Data_1_1Market_1_1RenkoBar.html',1,'QuantConnect::Data::Market']]],
  ['renkoconsolidator_9432',['RenkoConsolidator',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect.Data.Consolidators.RenkoConsolidator&lt; TInput &gt;'],['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect.Data.Consolidators.RenkoConsolidator']]],
  ['renkoconsolidator_3c_20t_20_3e_9433',['RenkoConsolidator&lt; T &gt;',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['rentandlandingfeescostofrevenueincomestatement_9434',['RentandLandingFeesCostofRevenueIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentandLandingFeesCostofRevenueIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['rentandlandingfeesincomestatement_9435',['RentAndLandingFeesIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentAndLandingFeesIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['rentexpensesupplementalincomestatement_9436',['RentExpenseSupplementalIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentExpenseSupplementalIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reorganizationothercostscashflowstatement_9437',['ReorganizationOtherCostsCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReorganizationOtherCostsCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['repaymentinleasefinancingcashflowstatement_9438',['RepaymentinLeaseFinancingCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepaymentinLeaseFinancingCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['repaymentofdebtcashflowstatement_9439',['RepaymentOfDebtCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepaymentOfDebtCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['report_9440',['Report',['../classQuantConnect_1_1Report_1_1Report.html',1,'QuantConnect::Report']]],
  ['reportargumentparser_9441',['ReportArgumentParser',['../classQuantConnect_1_1Configuration_1_1ReportArgumentParser.html',1,'QuantConnect::Configuration']]],
  ['reportednormalizedbasiceps_9442',['ReportedNormalizedBasicEPS',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReportedNormalizedBasicEPS.html',1,'QuantConnect::Data::Fundamental']]],
  ['reportednormalizeddilutedeps_9443',['ReportedNormalizedDilutedEPS',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReportedNormalizedDilutedEPS.html',1,'QuantConnect::Data::Fundamental']]],
  ['reportelement_9444',['ReportElement',['../classQuantConnect_1_1Report_1_1ReportElements_1_1ReportElement.html',1,'QuantConnect::Report::ReportElements']]],
  ['repurchaseofcapitalstockcashflowstatement_9445',['RepurchaseOfCapitalStockCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepurchaseOfCapitalStockCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['researchanddevelopmentexpensessupplementalincomestatement_9446',['ResearchAndDevelopmentExpensesSupplementalIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ResearchAndDevelopmentExpensesSupplementalIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['researchanddevelopmentincomestatement_9447',['ResearchAndDevelopmentIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ResearchAndDevelopmentIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reservedbuyingpowerforposition_9448',['ReservedBuyingPowerForPosition',['../classQuantConnect_1_1Securities_1_1ReservedBuyingPowerForPosition.html',1,'QuantConnect::Securities']]],
  ['reservedbuyingpowerforpositiongroup_9449',['ReservedBuyingPowerForPositionGroup',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerForPositionGroup.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerforpositiongroupparameters_9450',['ReservedBuyingPowerForPositionGroupParameters',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerForPositionGroupParameters.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerforpositionparameters_9451',['ReservedBuyingPowerForPositionParameters',['../classQuantConnect_1_1Securities_1_1ReservedBuyingPowerForPositionParameters.html',1,'QuantConnect::Securities']]],
  ['reservedbuyingpowerimpact_9452',['ReservedBuyingPowerImpact',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerImpact.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerimpactparameters_9453',['ReservedBuyingPowerImpactParameters',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerImpactParameters.html',1,'QuantConnect::Securities::Positions']]],
  ['restresponse_9454',['RestResponse',['../classQuantConnect_1_1Api_1_1RestResponse.html',1,'QuantConnect::Api']]],
  ['restrictedcashandcashequivalentsbalancesheet_9455',['RestrictedCashAndCashEquivalentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashAndCashEquivalentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcashandinvestmentsbalancesheet_9456',['RestrictedCashAndInvestmentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashAndInvestmentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcashbalancesheet_9457',['RestrictedCashBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcommonstockbalancesheet_9458',['RestrictedCommonStockBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCommonStockBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedinvestmentsbalancesheet_9459',['RestrictedInvestmentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedInvestmentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restructuringandmergernacquisitionincomestatement_9460',['RestructuringAndMergernAcquisitionIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestructuringAndMergernAcquisitionIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['restsubscriptionstreamreader_9461',['RestSubscriptionStreamReader',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Transport_1_1RestSubscriptionStreamReader.html',1,'QuantConnect::Lean::Engine::DataFeeds::Transport']]],
  ['result_9462',['Result',['../classQuantConnect_1_1Commands_1_1AddSecurityCommand_1_1Result.html',1,'QuantConnect.Commands.AddSecurityCommand.Result'],['../classQuantConnect_1_1Result.html',1,'QuantConnect.Result'],['../classQuantConnect_1_1Commands_1_1CancelOrderCommand_1_1Result.html',1,'QuantConnect.Commands.CancelOrderCommand.Result']]],
  ['resultsutil_9463',['ResultsUtil',['../classQuantConnect_1_1Report_1_1ResultsUtil.html',1,'QuantConnect::Report']]],
  ['retainedearningsbalancesheet_9464',['RetainedEarningsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RetainedEarningsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['returnssymboldata_9465',['ReturnsSymbolData',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1ReturnsSymbolData.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['returnssymboldataextensions_9466',['ReturnsSymbolDataExtensions',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1ReturnsSymbolDataExtensions.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['revenuegrowth_9467',['RevenueGrowth',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RevenueGrowth.html',1,'QuantConnect::Data::Fundamental']]],
  ['rickshawman_9468',['RickshawMan',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1RickshawMan.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['risefallthreemethods_9469',['RiseFallThreeMethods',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1RiseFallThreeMethods.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['riskmanagementmodel_9470',['RiskManagementModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Risk_1_1RiskManagementModel.html',1,'QuantConnect::Algorithm::Framework::Risk']]],
  ['riskmanagementmodelpythonwrapper_9471',['RiskManagementModelPythonWrapper',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Risk_1_1RiskManagementModelPythonWrapper.html',1,'QuantConnect::Algorithm::Framework::Risk']]],
  ['riskparityportfolioconstructionmodel_9472',['RiskParityPortfolioConstructionModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1RiskParityPortfolioConstructionModel.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['riskparityportfoliooptimizer_9473',['RiskParityPortfolioOptimizer',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1RiskParityPortfolioOptimizer.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['roa_9474',['ROA',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROA.html',1,'QuantConnect::Data::Fundamental']]],
  ['roa5yravg_9475',['ROA5YrAvg',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROA5YrAvg.html',1,'QuantConnect::Data::Fundamental']]],
  ['roe_9476',['ROE',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROE.html',1,'QuantConnect::Data::Fundamental']]],
  ['roe5yravg_9477',['ROE5YrAvg',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROE5YrAvg.html',1,'QuantConnect::Data::Fundamental']]],
  ['roic_9478',['ROIC',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROIC.html',1,'QuantConnect::Data::Fundamental']]],
  ['rolling_9479',['Rolling',['../classQuantConnect_1_1Report_1_1Rolling.html',1,'QuantConnect::Report']]],
  ['rollingwindow_9480',['RollingWindow',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20decimal_20_3e_9481',['RollingWindow&lt; decimal &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20double_20_3e_9482',['RollingWindow&lt; double &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20ibasedatabar_20_3e_9483',['RollingWindow&lt; IBaseDataBar &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20indicatordatapoint_20_3e_9484',['RollingWindow&lt; IndicatorDataPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20quantconnect_3a_3aindicators_3a_3aindicatordatapoint_20_3e_9485',['RollingWindow&lt; QuantConnect::Indicators::IndicatorDataPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20quantconnect_3a_3aindicators_3a_3apivotpoint_20_3e_9486',['RollingWindow&lt; QuantConnect::Indicators::PivotPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rsialphamodel_9487',['RsiAlphaModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1RsiAlphaModel.html',1,'QuantConnect::Algorithm::Framework::Alphas']]],
  ['runtimeerrorpacket_9488',['RuntimeErrorPacket',['../classQuantConnect_1_1Packets_1_1RuntimeErrorPacket.html',1,'QuantConnect::Packets']]]
];
