var searchData=
[
  ['randomdatagenerator_9682',['RandomDataGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomdatageneratorprogram_9683',['RandomDataGeneratorProgram',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGeneratorProgram.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomdatageneratorsettings_9684',['RandomDataGeneratorSettings',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGeneratorSettings.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randompricegenerator_9685',['RandomPriceGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomPriceGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomvaluegenerator_9686',['RandomValueGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomValueGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomvaluegeneratorexception_9687',['RandomValueGeneratorException',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomValueGeneratorException.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['rangebar_9688',['RangeBar',['../classQuantConnect_1_1Data_1_1Market_1_1RangeBar.html',1,'QuantConnect::Data::Market']]],
  ['rangeconsolidator_9689',['RangeConsolidator',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RangeConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['rategate_9690',['RateGate',['../classQuantConnect_1_1Util_1_1RateGate.html',1,'QuantConnect::Util']]],
  ['ratelimitenumerator_9691',['RateLimitEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1RateLimitEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['rateofchange_9692',['RateOfChange',['../classQuantConnect_1_1Indicators_1_1RateOfChange.html',1,'QuantConnect::Indicators']]],
  ['rateofchangepercent_9693',['RateOfChangePercent',['../classQuantConnect_1_1Indicators_1_1RateOfChangePercent.html',1,'QuantConnect::Indicators']]],
  ['rateofchangeratio_9694',['RateOfChangeRatio',['../classQuantConnect_1_1Indicators_1_1RateOfChangeRatio.html',1,'QuantConnect::Indicators']]],
  ['rawfileprocessor_9695',['RawFileProcessor',['../classQuantConnect_1_1ToolBox_1_1RawFileProcessor.html',1,'QuantConnect::ToolBox']]],
  ['rawmaterialsbalancesheet_9696',['RawMaterialsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RawMaterialsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['rbibrokeragemodel_9697',['RBIBrokerageModel',['../classQuantConnect_1_1Messages_1_1RBIBrokerageModel.html',1,'QuantConnect.Messages.RBIBrokerageModel'],['../classQuantConnect_1_1Brokerages_1_1RBIBrokerageModel.html',1,'QuantConnect.Brokerages.RBIBrokerageModel']]],
  ['rbifeemodel_9698',['RBIFeeModel',['../classQuantConnect_1_1Orders_1_1Fees_1_1RBIFeeModel.html',1,'QuantConnect::Orders::Fees']]],
  ['rbiorderproperties_9699',['RBIOrderProperties',['../classQuantConnect_1_1Orders_1_1RBIOrderProperties.html',1,'QuantConnect::Orders']]],
  ['readererrordetectedeventargs_9700',['ReaderErrorDetectedEventArgs',['../classQuantConnect_1_1ReaderErrorDetectedEventArgs.html',1,'QuantConnect']]],
  ['readererroreventargs_9701',['ReaderErrorEventArgs',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1ReaderErrorEventArgs.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['readerwriterlockslimextensions_9702',['ReaderWriterLockSlimExtensions',['../classQuantConnect_1_1Util_1_1ReaderWriterLockSlimExtensions.html',1,'QuantConnect::Util']]],
  ['readonlysecurityvaluescollection_9703',['ReadOnlySecurityValuesCollection',['../classQuantConnect_1_1Messages_1_1ReadOnlySecurityValuesCollection.html',1,'QuantConnect::Messages']]],
  ['realizedgainlossonsaleofloansandleasecashflowstatement_9704',['RealizedGainLossOnSaleOfLoansAndLeaseCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RealizedGainLossOnSaleOfLoansAndLeaseCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['realtimeprovider_9705',['RealTimeProvider',['../classQuantConnect_1_1RealTimeProvider.html',1,'QuantConnect']]],
  ['realtimescheduleeventservice_9706',['RealTimeScheduleEventService',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1RealTimeScheduleEventService.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['realtimesynchronizedtimer_9707',['RealTimeSynchronizedTimer',['../classQuantConnect_1_1RealTimeSynchronizedTimer.html',1,'QuantConnect']]],
  ['receiptsfromcustomerscashflowstatement_9708',['ReceiptsfromCustomersCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceiptsfromCustomersCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['receiptsfromgovernmentgrantscashflowstatement_9709',['ReceiptsfromGovernmentGrantsCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceiptsfromGovernmentGrantsCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivablesadjustmentsallowancesbalancesheet_9710',['ReceivablesAdjustmentsAllowancesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivablesAdjustmentsAllowancesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivablesbalancesheet_9711',['ReceivablesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivablesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivableturnover_9712',['ReceivableTurnover',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivableTurnover.html',1,'QuantConnect::Data::Fundamental']]],
  ['reconciledcostofrevenueincomestatement_9713',['ReconciledCostOfRevenueIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReconciledCostOfRevenueIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reconcileddepreciationincomestatement_9714',['ReconciledDepreciationIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReconciledDepreciationIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['ref_9715',['Ref',['../classQuantConnect_1_1Util_1_1Ref.html',1,'QuantConnect::Util']]],
  ['ref_3c_20timespan_20_3e_9716',['Ref&lt; TimeSpan &gt;',['../classQuantConnect_1_1Util_1_1Ref.html',1,'QuantConnect::Util']]],
  ['referencewrapper_9717',['ReferenceWrapper',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['referencewrapper_3c_20datetime_20_3e_9718',['ReferenceWrapper&lt; DateTime &gt;',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['referencewrapper_3c_20decimal_20_3e_9719',['ReferenceWrapper&lt; decimal &gt;',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['refreshenumerator_9720',['RefreshEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1RefreshEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['registeredsecuritydatatypesprovider_9721',['RegisteredSecurityDataTypesProvider',['../classQuantConnect_1_1Messages_1_1RegisteredSecurityDataTypesProvider.html',1,'QuantConnect.Messages.RegisteredSecurityDataTypesProvider'],['../classQuantConnect_1_1Securities_1_1RegisteredSecurityDataTypesProvider.html',1,'QuantConnect.Securities.RegisteredSecurityDataTypesProvider']]],
  ['regressionchannel_9722',['RegressionChannel',['../classQuantConnect_1_1Indicators_1_1RegressionChannel.html',1,'QuantConnect::Indicators']]],
  ['regressionfileloghandler_9723',['RegressionFileLogHandler',['../classQuantConnect_1_1Logging_1_1RegressionFileLogHandler.html',1,'QuantConnect::Logging']]],
  ['regressiongrowthofdividends5years_9724',['RegressionGrowthofDividends5Years',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegressionGrowthofDividends5Years.html',1,'QuantConnect::Data::Fundamental']]],
  ['regressiongrowthoperatingrevenue5years_9725',['RegressionGrowthOperatingRevenue5Years',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegressionGrowthOperatingRevenue5Years.html',1,'QuantConnect::Data::Fundamental']]],
  ['regressionresulthandler_9726',['RegressionResultHandler',['../classQuantConnect_1_1Lean_1_1Engine_1_1Results_1_1RegressionResultHandler.html',1,'QuantConnect::Lean::Engine::Results']]],
  ['regularexpression_9727',['RegularExpression',['../classQuantConnect_1_1Util_1_1Validate_1_1RegularExpression.html',1,'QuantConnect::Util::Validate']]],
  ['regulatoryassetsbalancesheet_9728',['RegulatoryAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegulatoryAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['regulatoryliabilitiesbalancesheet_9729',['RegulatoryLiabilitiesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegulatoryLiabilitiesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsuranceandotherrecoveriesreceivedcashflowstatement_9730',['ReinsuranceandOtherRecoveriesReceivedCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceandOtherRecoveriesReceivedCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsuranceassetsbalancesheet_9731',['ReinsuranceAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancebalancespayablebalancesheet_9732',['ReinsuranceBalancesPayableBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceBalancesPayableBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoverablebalancesheet_9733',['ReinsuranceRecoverableBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoverableBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesclaimsandbenefitsincomestatement_9734',['ReinsuranceRecoveriesClaimsandBenefitsIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesClaimsandBenefitsIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesofinsuranceliabilitiesincomestatement_9735',['ReinsuranceRecoveriesofInsuranceLiabilitiesIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesofInsuranceLiabilitiesIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesofinvestmentcontractincomestatement_9736',['ReinsuranceRecoveriesofInvestmentContractIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesofInvestmentContractIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['relativedailyvolume_9737',['RelativeDailyVolume',['../classQuantConnect_1_1Indicators_1_1RelativeDailyVolume.html',1,'QuantConnect::Indicators']]],
  ['relativemovingaverage_9738',['RelativeMovingAverage',['../classQuantConnect_1_1Indicators_1_1RelativeMovingAverage.html',1,'QuantConnect::Indicators']]],
  ['relativestandarddeviationvolatilitymodel_9739',['RelativeStandardDeviationVolatilityModel',['../classQuantConnect_1_1Securities_1_1RelativeStandardDeviationVolatilityModel.html',1,'QuantConnect::Securities']]],
  ['relativestrengthindex_9740',['RelativeStrengthIndex',['../classQuantConnect_1_1Indicators_1_1RelativeStrengthIndex.html',1,'QuantConnect::Indicators']]],
  ['relativevigorindex_9741',['RelativeVigorIndex',['../classQuantConnect_1_1Indicators_1_1RelativeVigorIndex.html',1,'QuantConnect::Indicators']]],
  ['relativevigorindexsignal_9742',['RelativeVigorIndexSignal',['../classQuantConnect_1_1Indicators_1_1RelativeVigorIndexSignal.html',1,'QuantConnect::Indicators']]],
  ['remotefilesubscriptionstreamreader_9743',['RemoteFileSubscriptionStreamReader',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Transport_1_1RemoteFileSubscriptionStreamReader.html',1,'QuantConnect::Lean::Engine::DataFeeds::Transport']]],
  ['removedmember_9744',['RemovedMember',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1PendingRemovalsManager_1_1RemovedMember.html',1,'QuantConnect::Lean::Engine::DataFeeds::PendingRemovalsManager']]],
  ['renkobar_9745',['RenkoBar',['../classQuantConnect_1_1Data_1_1Market_1_1RenkoBar.html',1,'QuantConnect::Data::Market']]],
  ['renkoconsolidator_9746',['RenkoConsolidator',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect.Data.Consolidators.RenkoConsolidator&lt; TInput &gt;'],['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect.Data.Consolidators.RenkoConsolidator']]],
  ['renkoconsolidator_3c_20t_20_3e_9747',['RenkoConsolidator&lt; T &gt;',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['rentandlandingfeescostofrevenueincomestatement_9748',['RentandLandingFeesCostofRevenueIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentandLandingFeesCostofRevenueIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['rentandlandingfeesincomestatement_9749',['RentAndLandingFeesIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentAndLandingFeesIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['rentexpensesupplementalincomestatement_9750',['RentExpenseSupplementalIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentExpenseSupplementalIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reorganizationothercostscashflowstatement_9751',['ReorganizationOtherCostsCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReorganizationOtherCostsCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['repaymentinleasefinancingcashflowstatement_9752',['RepaymentinLeaseFinancingCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepaymentinLeaseFinancingCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['repaymentofdebtcashflowstatement_9753',['RepaymentOfDebtCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepaymentOfDebtCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['report_9754',['Report',['../classQuantConnect_1_1Report_1_1Report.html',1,'QuantConnect::Report']]],
  ['reportargumentparser_9755',['ReportArgumentParser',['../classQuantConnect_1_1Configuration_1_1ReportArgumentParser.html',1,'QuantConnect::Configuration']]],
  ['reportednormalizedbasiceps_9756',['ReportedNormalizedBasicEPS',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReportedNormalizedBasicEPS.html',1,'QuantConnect::Data::Fundamental']]],
  ['reportednormalizeddilutedeps_9757',['ReportedNormalizedDilutedEPS',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReportedNormalizedDilutedEPS.html',1,'QuantConnect::Data::Fundamental']]],
  ['reportelement_9758',['ReportElement',['../classQuantConnect_1_1Report_1_1ReportElements_1_1ReportElement.html',1,'QuantConnect::Report::ReportElements']]],
  ['repurchaseofcapitalstockcashflowstatement_9759',['RepurchaseOfCapitalStockCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepurchaseOfCapitalStockCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['researchanddevelopmentexpensessupplementalincomestatement_9760',['ResearchAndDevelopmentExpensesSupplementalIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ResearchAndDevelopmentExpensesSupplementalIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['researchanddevelopmentincomestatement_9761',['ResearchAndDevelopmentIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ResearchAndDevelopmentIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reservedbuyingpowerforposition_9762',['ReservedBuyingPowerForPosition',['../classQuantConnect_1_1Securities_1_1ReservedBuyingPowerForPosition.html',1,'QuantConnect::Securities']]],
  ['reservedbuyingpowerforpositiongroup_9763',['ReservedBuyingPowerForPositionGroup',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerForPositionGroup.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerforpositiongroupparameters_9764',['ReservedBuyingPowerForPositionGroupParameters',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerForPositionGroupParameters.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerforpositionparameters_9765',['ReservedBuyingPowerForPositionParameters',['../classQuantConnect_1_1Securities_1_1ReservedBuyingPowerForPositionParameters.html',1,'QuantConnect::Securities']]],
  ['reservedbuyingpowerimpact_9766',['ReservedBuyingPowerImpact',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerImpact.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerimpactparameters_9767',['ReservedBuyingPowerImpactParameters',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerImpactParameters.html',1,'QuantConnect::Securities::Positions']]],
  ['resetcompositeindicator_9768',['ResetCompositeIndicator',['../classQuantConnect_1_1Indicators_1_1ResetCompositeIndicator.html',1,'QuantConnect::Indicators']]],
  ['restresponse_9769',['RestResponse',['../classQuantConnect_1_1Api_1_1RestResponse.html',1,'QuantConnect::Api']]],
  ['restrictedcashandcashequivalentsbalancesheet_9770',['RestrictedCashAndCashEquivalentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashAndCashEquivalentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcashandinvestmentsbalancesheet_9771',['RestrictedCashAndInvestmentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashAndInvestmentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcashbalancesheet_9772',['RestrictedCashBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcommonstockbalancesheet_9773',['RestrictedCommonStockBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCommonStockBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedinvestmentsbalancesheet_9774',['RestrictedInvestmentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedInvestmentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restructuringandmergernacquisitionincomestatement_9775',['RestructuringAndMergernAcquisitionIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestructuringAndMergernAcquisitionIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['restsubscriptionstreamreader_9776',['RestSubscriptionStreamReader',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Transport_1_1RestSubscriptionStreamReader.html',1,'QuantConnect::Lean::Engine::DataFeeds::Transport']]],
  ['result_9777',['Result',['../classQuantConnect_1_1Commands_1_1CancelOrderCommand_1_1Result.html',1,'QuantConnect.Commands.CancelOrderCommand.Result'],['../classQuantConnect_1_1Commands_1_1AddSecurityCommand_1_1Result.html',1,'QuantConnect.Commands.AddSecurityCommand.Result'],['../classQuantConnect_1_1Result.html',1,'QuantConnect.Result']]],
  ['resulthandlerinitializeparameters_9778',['ResultHandlerInitializeParameters',['../classQuantConnect_1_1Lean_1_1Engine_1_1Results_1_1ResultHandlerInitializeParameters.html',1,'QuantConnect::Lean::Engine::Results']]],
  ['resultsutil_9779',['ResultsUtil',['../classQuantConnect_1_1Report_1_1ResultsUtil.html',1,'QuantConnect::Report']]],
  ['retainedearningsbalancesheet_9780',['RetainedEarningsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RetainedEarningsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['returnssymboldata_9781',['ReturnsSymbolData',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1ReturnsSymbolData.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['returnssymboldataextensions_9782',['ReturnsSymbolDataExtensions',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1ReturnsSymbolDataExtensions.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['revenuegrowth_9783',['RevenueGrowth',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RevenueGrowth.html',1,'QuantConnect::Data::Fundamental']]],
  ['rho_9784',['Rho',['../classQuantConnect_1_1Indicators_1_1Rho.html',1,'QuantConnect::Indicators']]],
  ['rickshawman_9785',['RickshawMan',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1RickshawMan.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['risefallthreemethods_9786',['RiseFallThreeMethods',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1RiseFallThreeMethods.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['riskfreeinterestratemodelextensions_9787',['RiskFreeInterestRateModelExtensions',['../classQuantConnect_1_1Data_1_1RiskFreeInterestRateModelExtensions.html',1,'QuantConnect::Data']]],
  ['riskfreeinterestratemodelpythonwrapper_9788',['RiskFreeInterestRateModelPythonWrapper',['../classQuantConnect_1_1Python_1_1RiskFreeInterestRateModelPythonWrapper.html',1,'QuantConnect::Python']]],
  ['riskmanagementmodel_9789',['RiskManagementModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Risk_1_1RiskManagementModel.html',1,'QuantConnect::Algorithm::Framework::Risk']]],
  ['riskmanagementmodelpythonwrapper_9790',['RiskManagementModelPythonWrapper',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Risk_1_1RiskManagementModelPythonWrapper.html',1,'QuantConnect::Algorithm::Framework::Risk']]],
  ['riskparityportfolioconstructionmodel_9791',['RiskParityPortfolioConstructionModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1RiskParityPortfolioConstructionModel.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['riskparityportfoliooptimizer_9792',['RiskParityPortfolioOptimizer',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1RiskParityPortfolioOptimizer.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['roa_9793',['ROA',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROA.html',1,'QuantConnect::Data::Fundamental']]],
  ['roa5yravg_9794',['ROA5YrAvg',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROA5YrAvg.html',1,'QuantConnect::Data::Fundamental']]],
  ['roe_9795',['ROE',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROE.html',1,'QuantConnect::Data::Fundamental']]],
  ['roe5yravg_9796',['ROE5YrAvg',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROE5YrAvg.html',1,'QuantConnect::Data::Fundamental']]],
  ['roic_9797',['ROIC',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROIC.html',1,'QuantConnect::Data::Fundamental']]],
  ['rolling_9798',['Rolling',['../classQuantConnect_1_1Report_1_1Rolling.html',1,'QuantConnect::Report']]],
  ['rollingwindow_9799',['RollingWindow',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect.Indicators.RollingWindow&lt; T &gt;'],['../classQuantConnect_1_1Messages_1_1RollingWindow.html',1,'QuantConnect.Messages.RollingWindow']]],
  ['rollingwindow_3c_20decimal_20_3e_9800',['RollingWindow&lt; decimal &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20double_20_3e_9801',['RollingWindow&lt; double &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20ibasedatabar_20_3e_9802',['RollingWindow&lt; IBaseDataBar &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20indicatordatapoint_20_3e_9803',['RollingWindow&lt; IndicatorDataPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20quantconnect_3a_3aindicators_3a_3aindicatordatapoint_20_3e_9804',['RollingWindow&lt; QuantConnect::Indicators::IndicatorDataPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20quantconnect_3a_3aindicators_3a_3apivotpoint_20_3e_9805',['RollingWindow&lt; QuantConnect::Indicators::PivotPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rsialphamodel_9806',['RsiAlphaModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1RsiAlphaModel.html',1,'QuantConnect::Algorithm::Framework::Alphas']]],
  ['runtimeerrorpacket_9807',['RuntimeErrorPacket',['../classQuantConnect_1_1Packets_1_1RuntimeErrorPacket.html',1,'QuantConnect::Packets']]]
];
